# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyfilter_filter_config_widget.ui'
#
# Created: Sat Feb 28 19:23:43 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget_Filter_Config(object):
    def setupUi(self, DockWidget_Filter_Config):
        DockWidget_Filter_Config.setObjectName(_fromUtf8("DockWidget_Filter_Config"))
        DockWidget_Filter_Config.resize(413, 421)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 120, 80))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButton_Analog = QtGui.QRadioButton(self.groupBox)
        self.radioButton_Analog.setGeometry(QtCore.QRect(10, 20, 104, 21))
        self.radioButton_Analog.setChecked(True)
        self.radioButton_Analog.setObjectName(_fromUtf8("radioButton_Analog"))
        self.radioButton_Digital = QtGui.QRadioButton(self.groupBox)
        self.radioButton_Digital.setGeometry(QtCore.QRect(10, 40, 104, 21))
        self.radioButton_Digital.setObjectName(_fromUtf8("radioButton_Digital"))
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 70, 191, 121))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButton_Butterworth = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Butterworth.setGeometry(QtCore.QRect(10, 40, 104, 21))
        self.radioButton_Butterworth.setObjectName(_fromUtf8("radioButton_Butterworth"))
        self.radioButton_Cheby1 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Cheby1.setGeometry(QtCore.QRect(10, 60, 161, 21))
        self.radioButton_Cheby1.setObjectName(_fromUtf8("radioButton_Cheby1"))
        self.radioButton_Cheby2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Cheby2.setGeometry(QtCore.QRect(10, 80, 131, 21))
        self.radioButton_Cheby2.setObjectName(_fromUtf8("radioButton_Cheby2"))
        self.radioButton_Elliptical = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Elliptical.setGeometry(QtCore.QRect(10, 100, 104, 21))
        self.radioButton_Elliptical.setObjectName(_fromUtf8("radioButton_Elliptical"))
        self.radioButton_Bessel = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_Bessel.setGeometry(QtCore.QRect(10, 20, 104, 21))
        self.radioButton_Bessel.setChecked(True)
        self.radioButton_Bessel.setObjectName(_fromUtf8("radioButton_Bessel"))
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 210, 171, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButton_LP = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_LP.setGeometry(QtCore.QRect(10, 20, 104, 21))
        self.radioButton_LP.setChecked(True)
        self.radioButton_LP.setObjectName(_fromUtf8("radioButton_LP"))
        self.radioButton_HP = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_HP.setGeometry(QtCore.QRect(10, 40, 104, 21))
        self.radioButton_HP.setObjectName(_fromUtf8("radioButton_HP"))
        self.radioButton_BP = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_BP.setGeometry(QtCore.QRect(10, 60, 104, 21))
        self.radioButton_BP.setObjectName(_fromUtf8("radioButton_BP"))
        self.radioButton_BS = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_BS.setGeometry(QtCore.QRect(10, 80, 104, 21))
        self.radioButton_BS.setObjectName(_fromUtf8("radioButton_BS"))
        self.radioButton_AP = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_AP.setGeometry(QtCore.QRect(10, 100, 104, 21))
        self.radioButton_AP.setObjectName(_fromUtf8("radioButton_AP"))
        self.groupBox_4 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_4.setGeometry(QtCore.QRect(200, 0, 211, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radioButton_NWn = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_NWn.setGeometry(QtCore.QRect(0, 20, 104, 21))
        self.radioButton_NWn.setChecked(True)
        self.radioButton_NWn.setObjectName(_fromUtf8("radioButton_NWn"))
        self.radioButton_AttSpecs = QtGui.QRadioButton(self.groupBox_4)
        self.radioButton_AttSpecs.setGeometry(QtCore.QRect(0, 40, 171, 21))
        self.radioButton_AttSpecs.setObjectName(_fromUtf8("radioButton_AttSpecs"))
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 360, 85, 26))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 360, 131, 26))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 360, 85, 26))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_5.setGeometry(QtCore.QRect(200, 70, 221, 171))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_opt1 = QtGui.QLabel(self.groupBox_5)
        self.label_opt1.setGeometry(QtCore.QRect(0, 20, 56, 20))
        self.label_opt1.setObjectName(_fromUtf8("label_opt1"))
        self.label_opt2 = QtGui.QLabel(self.groupBox_5)
        self.label_opt2.setGeometry(QtCore.QRect(0, 60, 56, 20))
        self.label_opt2.setObjectName(_fromUtf8("label_opt2"))
        self.plainTextEdit_opt1 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_opt1.setGeometry(QtCore.QRect(30, 20, 151, 31))
        self.plainTextEdit_opt1.setObjectName(_fromUtf8("plainTextEdit_opt1"))
        self.plainTextEdit_opt2 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_opt2.setGeometry(QtCore.QRect(30, 60, 151, 31))
        self.plainTextEdit_opt2.setObjectName(_fromUtf8("plainTextEdit_opt2"))
        self.label_opt3 = QtGui.QLabel(self.groupBox_5)
        self.label_opt3.setGeometry(QtCore.QRect(0, 100, 31, 20))
        self.label_opt3.setObjectName(_fromUtf8("label_opt3"))
        self.plainTextEdit_opt3 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_opt3.setGeometry(QtCore.QRect(30, 100, 151, 31))
        self.plainTextEdit_opt3.setObjectName(_fromUtf8("plainTextEdit_opt3"))
        self.label_opt4 = QtGui.QLabel(self.groupBox_5)
        self.label_opt4.setGeometry(QtCore.QRect(0, 140, 31, 20))
        self.label_opt4.setObjectName(_fromUtf8("label_opt4"))
        self.plainTextEdit_opt4 = QtGui.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_opt4.setGeometry(QtCore.QRect(30, 140, 151, 31))
        self.plainTextEdit_opt4.setObjectName(_fromUtf8("plainTextEdit_opt4"))
        self.groupBox_6 = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_6.setGeometry(QtCore.QRect(200, 250, 181, 80))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.radioButton_matchPB = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_matchPB.setGeometry(QtCore.QRect(0, 30, 171, 21))
        self.radioButton_matchPB.setObjectName(_fromUtf8("radioButton_matchPB"))
        self.radioButton_matchSB = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_matchSB.setGeometry(QtCore.QRect(0, 60, 141, 21))
        self.radioButton_matchSB.setObjectName(_fromUtf8("radioButton_matchSB"))
        DockWidget_Filter_Config.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_Filter_Config)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_Filter_Config)

    def retranslateUi(self, DockWidget_Filter_Config):
        DockWidget_Filter_Config.setWindowTitle(_translate("DockWidget_Filter_Config", "Filter settings", None))
        self.groupBox.setTitle(_translate("DockWidget_Filter_Config", "Analog or digital?", None))
        self.radioButton_Analog.setText(_translate("DockWidget_Filter_Config", "Analog", None))
        self.radioButton_Digital.setText(_translate("DockWidget_Filter_Config", "Digital", None))
        self.groupBox_2.setTitle(_translate("DockWidget_Filter_Config", "Filter topology", None))
        self.radioButton_Butterworth.setText(_translate("DockWidget_Filter_Config", "Butterworth", None))
        self.radioButton_Cheby1.setText(_translate("DockWidget_Filter_Config", "Chebyshev Type1", None))
        self.radioButton_Cheby2.setText(_translate("DockWidget_Filter_Config", "Chebyshev Type2", None))
        self.radioButton_Elliptical.setText(_translate("DockWidget_Filter_Config", "Elliptical", None))
        self.radioButton_Bessel.setText(_translate("DockWidget_Filter_Config", "Bessel", None))
        self.groupBox_3.setTitle(_translate("DockWidget_Filter_Config", "Filter type", None))
        self.radioButton_LP.setText(_translate("DockWidget_Filter_Config", "Low-pass", None))
        self.radioButton_HP.setText(_translate("DockWidget_Filter_Config", "High-pass", None))
        self.radioButton_BP.setText(_translate("DockWidget_Filter_Config", "Band-pass", None))
        self.radioButton_BS.setText(_translate("DockWidget_Filter_Config", "Band-stop", None))
        self.radioButton_AP.setText(_translate("DockWidget_Filter_Config", "All-pass", None))
        self.groupBox_4.setTitle(_translate("DockWidget_Filter_Config", "Parameter calculation...", None))
        self.radioButton_NWn.setText(_translate("DockWidget_Filter_Config", "From N, Wn", None))
        self.radioButton_AttSpecs.setText(_translate("DockWidget_Filter_Config", "From attenuation specs", None))
        self.pushButton.setText(_translate("DockWidget_Filter_Config", "Design", None))
        self.pushButton_2.setText(_translate("DockWidget_Filter_Config", "Show coefficients", None))
        self.pushButton_3.setText(_translate("DockWidget_Filter_Config", "Refresh plot", None))
        self.groupBox_5.setTitle(_translate("DockWidget_Filter_Config", "Filter specs", None))
        self.label_opt1.setText(_translate("DockWidget_Filter_Config", "N:", None))
        self.label_opt2.setText(_translate("DockWidget_Filter_Config", "Wn:", None))
        self.label_opt3.setText(_translate("DockWidget_Filter_Config", "Fc:", None))
        self.label_opt4.setText(_translate("DockWidget_Filter_Config", "Fs:", None))
        self.groupBox_6.setTitle(_translate("DockWidget_Filter_Config", "Options", None))
        self.radioButton_matchPB.setText(_translate("DockWidget_Filter_Config", "Match passband", None))
        self.radioButton_matchSB.setText(_translate("DockWidget_Filter_Config", "Match stopband", None))

